python colorSchemeTool.py "tmThemes\Active4D.tmTheme" "intellijThemes\Active4D.icls"
python colorSchemeTool.py "tmThemes\All Hallow's Eve.tmTheme" "intellijThemes\All Hallow's Eve.icls"
python colorSchemeTool.py "tmThemes\Amy.tmTheme" "intellijThemes\Amy.icls"
python colorSchemeTool.py "tmThemes\Blackboard.tmTheme" "intellijThemes\Blackboard.icls"
python colorSchemeTool.py "tmThemes\Cobalt.tmTheme" "intellijThemes\Cobalt.icls"
python colorSchemeTool.py "tmThemes\Dawn.tmTheme" "intellijThemes\Dawn.icls"
python colorSchemeTool.py "tmThemes\Eiffel.tmTheme" "intellijThemes\Eiffel.icls"
python colorSchemeTool.py "tmThemes\Espresso Libre.tmTheme" "intellijThemes\Espresso Libre.icls"
python colorSchemeTool.py "tmThemes\IDLE.tmTheme" "intellijThemes\IDLE.icls"
::python colorSchemeTool.py "tmThemes\LAZY.tmTheme" "intellijThemes\LAZY.icls"
python colorSchemeTool.py "tmThemes\Mac Classic.tmTheme" "intellijThemes\Mac Classic.icls"
::python colorSchemeTool.py "tmThemes\MagicWB (Amiga).tmTheme" "intellijThemes\MagicWB (Amiga).icls"
::python colorSchemeTool.py "tmThemes\Monokai Bright.tmTheme" "intellijThemes\Monokai Bright.icls"
python colorSchemeTool.py "tmThemes\Monokai.tmTheme" "intellijThemes\Monokai.icls"
python colorSchemeTool.py "tmThemes\Pastels on Dark.tmTheme" "intellijThemes\Pastels on Dark.icls"
python colorSchemeTool.py "tmThemes\Railscasts.tmTheme" "intellijThemes\Railscasts.icls"
python colorSchemeTool.py "tmThemes\Slush & Poppies.tmTheme" "intellijThemes\Slush & Poppies.icls"
::python colorSchemeTool.py "tmThemes\SpaceCadet.tmTheme" "intellijThemes\SpaceCadet.icls"
python colorSchemeTool.py "tmThemes\Sunburst.tmTheme" "intellijThemes\Sunburst.icls"
python colorSchemeTool.py "tmThemes\Twilight.tmTheme" "intellijThemes\Twilight.icls"
::python colorSchemeTool.py "tmThemes\Zenburnesque.tmTheme" "intellijThemes\Zenburnesque.icls"
python colorSchemeTool.py "tmThemes\iPlastic.tmTheme" "intellijThemes\iPlastic.icls"
